name: focusnest
description: "Flutter time management app"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_core_platform_interface: ^5.0.0

  json_annotation: ^4.9.0
  freezed_annotation:
    ^2.4.1

    # riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  logger: ^2.2.0

  # testing
  mockito: ^5.4.4
  mocktail: ^1.0.3

  # routing
  go_router: ^14.1.0

  # drift
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  sqlite3: ^2.4.3
  uuid: ^4.4.0

  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0
  table_calendar: ^3.1.1
  intl: ^0.19.0

  # Notifications
  awesome_notifications_core: ^0.9.3
  awesome_notifications: any
  audioplayers: ^6.0.0

  # package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  drift_dev: ^2.18.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/focusnest-icon.png
    - assets/sounds/timer-completion.m4a
