name: CI/CD on Development Merge

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"
          cache: "gradle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Set Environment Variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.DEV_ANDROID_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.DEV_ANDROID_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.DEV_WEB_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "IOS_BUNDLE_ID=${{ secrets.DEV_IOS_BUNDLE_ID }}" >> $GITHUB_ENV

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.DEV_GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ./ios/Runner/GoogleService-Info.plist

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.DEV_GOOGLE_SERVICES_JSON }}" | base64 --decode > ./android/app/google-services.json

      - name: Generate Firebase Options
        run: dart tool/generate_firebase_options_dev.dart

      - name: Run tests
        run: flutter test

      - name: Build Debug APK
        run: flutter build apk --debug --target=lib/main_development.dart

      - name: Build Debug iOS App
        run: flutter build ios --debug --no-codesign --target=lib/main_development.dart
