name: Restrict Merges to Production

on:
  pull_request:
    branches:
      - production

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check if source branch is staging
        run: |
          if [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "Error: Only the 'staging' branch can be merged into production."
            exit 1
          fi
